# Generated by Django 5.0.3 on 2024-03-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0003_addproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Addproduct',
        ),
    ]
