# Generated by Django 5.0.3 on 2024-03-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0004_post_delete_addproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-01 12:00:00'),
            preserve_default=False,
        ),
    ]
