# Generated by Django 5.0.3 on 2024-11-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0011_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
