# Generated by Django 5.0.3 on 2024-12-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0012_delete_customgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students/profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
