# Generated by Django 5.0.3 on 2024-12-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0016_category_remove_purchase_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
