# Generated by Django 5.0.3 on 2024-12-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0017_purchase_category_sale_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='measurement_unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('meter', 'Meter'), ('kg', 'Kg'), ('liter', 'Liter'), ('piece', 'Piece'), ('box', 'Box'), ('cm', 'Cm'), ('gm', 'Gram'), ('other', 'Other')], default='nos', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='measurement_unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('meter', 'Meter'), ('kg', 'Kg'), ('liter', 'Liter'), ('piece', 'Piece'), ('box', 'Box'), ('cm', 'Cm'), ('gm', 'Gram'), ('other', 'Other')], default='nos', max_length=50),
        ),
    ]
