# Generated by Django 5.0.3 on 2024-12-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0022_alter_purchase_box_type_alter_sale_box_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
