# Generated by Django 5.0.3 on 2024-12-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0023_alter_purchase_category_alter_sale_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
