# Generated by Django 5.0.3 on 2024-12-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0025_returnproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnProduct',
        ),
    ]
