# Generated by Django 5.0.3 on 2024-12-07 22:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0026_delete_returnproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_to', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('serial_no', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('verified_by', models.CharField(max_length=255)),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='autheticatweb.measurementunit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='autheticatweb.product')),
            ],
        ),
    ]
