# Generated by Django 5.0.3 on 2024-12-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0027_return'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
