# Generated by Django 5.0.3 on 2024-12-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0029_rowstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RowState',
        ),
    ]
