# Generated by Django 5.0.3 on 2024-12-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0032_alter_returneditem_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discription',
            field=models.CharField(default='Thankyou', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='discription',
            field=models.CharField(default='Thankyou', max_length=255),
        ),
    ]
