# Generated by Django 5.0.3 on 2024-12-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0033_purchase_discription_sale_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='discription',
            new_name='description',
        ),
    ]
