# Generated by Django 5.0.3 on 2024-12-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autheticatweb', '0034_rename_discription_purchase_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='rms_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='rms_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
